blog/auth.py
from flask_login import login_user, logout_user, current_user, login_required
from .forms import SignupForm, LoginForm
from .models import db, get_user_model
from flask import Blueprint, render_template, request, url_for, flash
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])  # 로그인에서 POST 요청을 처리해야 함.
def login():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():

        # 폼으로부터 검증된 데이터 받아오기
        password = form.password.data

        # 폼에서 받아온 이메일로 유저 찾기
        user = get_user_model().query.filter_by(email=form.email.data).first()

        # 로그인 폼에서 입력된 이메일이 존재한다면,
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("Password is incorrect!", category='error')
        # 로그인 폼에서 입력된 이메일이 존재하지 않는다면,
        else:
            flash("Email does not exist...", category='error')

    return render_template("login.html", form=form, user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))  # 로그아웃하면 views의 blog_home으로 리다이렉트됨


@auth.route("/sign-up", methods=['GET', 'POST'])  # 회원가입에서 POST 요청을 처리해야 함.
def signup():
    form = SignupForm()
    if request.method == "POST" and form.validate_on_submit():
        # 폼으로부터 검증된 데이터 받아오기
        signup_user = get_user_model()(
            email=form.email.data,
            username=form.username.data,
            password=generate_password_hash(form.password1.data),
        )

        # 폼에서 받아온 데이터가 데이터베이스에 이미 존재하는지 확인
        email_exists = get_user_model().query.filter_by(email=form.email.data).first()
        username_exists = get_user_model().query.filter_by(username=form.username.data).first()



        # 이메일 중복 검사
        if email_exists:
            flash("이메일이 이미 존재합니다...", category='error')
        # 유저네임 중복 검사
        elif username_exists:
            flash("유저네임이 중복됩니다...", category='error')
        # 위의 모든 과정을 통과한다면, 폼에서 받아온 데이터를 새로운 유저로서 저장
        else:
            db.session.add(signup_user)
            db.session.commit()
            flash("User created!!!")
            return redirect(url_for("views.home")) # 저장이 완료된 후 home으로 리다이렉트

    # GET요청을 보낸다면 회원가입 템플릿을 보여줌
    return render_template("signup.html", form=form, user=current_user)

blog/views.py
from flask import Blueprint, render_template, request, redirect, url_for, abort
from flask_login import current_user, login_required
from .models import get_category_model, get_post_model, db, get_comment_model
from .forms import PostForm, CommentForm

views = Blueprint("views", __name__)


@views.route("/")
@views.route("/home")
def home():
    return render_template("index.html", user=current_user)


@views.route("/about")
def about():
    return render_template("about.html", user=current_user)


@views.route("/create-post", methods=['GET', 'POST'])
@login_required
def create_post():
    if current_user.is_staff == True:
        form = PostForm()
        if request.method == "POST" and form.validate_on_submit():
            post = get_post_model()(
                title=form.title.data,
                content=form.content.data,
                category_id=form.category.data,
                author_id=current_user.id,
            )
            db.session.add(post)
            db.session.commit()
            return redirect(url_for("views.home"))
        else:
            categories = get_category_model().query.all()
            return render_template("post_create_form.html", user=current_user, categories=categories, form=form)
    else:
        return abort(403)


@views.route("/edit-post/<int:id>", methods=["GET", "POST"])
@login_required
def edit_post(id):
    post = get_post_model().query.filter_by(id=id).first()  # id로부터 포스트를 가져오고,
    form = PostForm()  # form 을 사용할 것이므로 가져와 준다.
    categories = get_category_model().query.all()  # category 들도 모두 가져와 준다.

    # 현재 유저는 스태프 권한을 가지고 있어야 하고, 작성자만 게시물을 수정할 수 있어야 한다.
    if current_user.is_staff == True and current_user.username == post.user.username:
        if request.method == "GET":
            return render_template("post_edit_form.html", user=current_user, post=post, categories=categories,
                                   form=form)
        elif request.method == "POST" and form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            post.category_id = int(form.category.data)
            db.session.commit()
            return redirect(url_for("views.home"))
    # 스태프 권한을 가지고 있지 않거나, 게시물의 작성자가 아닐 경우 403 error를 발생시킨다.
    else:
        abort(403)


# 모든 카테고리들의 목록을 보여줌
@views.route("/categories-list")
def categories_list():
    categories = get_category_model().query.all()  # 모든 카테고리들을 가져오고,
    # 아래에서 context 로 그것을 추가해 준다.
    return render_template("categories_list.html", user=current_user, categories=categories)


# /post-list/카테고리 id 로 해당 카테고리에 속한 모든 포스트들을 보여줌
@views.route("/post-list/<int:id>")
def post_list(id):
    current_category = get_category_model().query.filter_by(id=id).first()
    posts = get_post_model().query.filter_by(category_id=id)
    return render_template("post_list.html", user=current_user, posts=posts, current_category=current_category)


# /posts/게시물의 id 로 포스트 정보를 보여줌
@views.route('/posts/<int:id>')
def post_detail(id):
    comment_form = CommentForm()
    post = get_post_model().query.filter_by(id=id).first()
    comments = get_post_model().query.filter_by(id=id).first().comments # id에 맞는 포스트 모델을 가져와서, 해당 게시물에 달린 모든 댓글들을 가져옴
    return render_template("post_detail.html", user=current_user, post=post, comments=comments, form=comment_form)


@login_required
@views.route("/create-comment/<int:id>", methods=['POST'])
def create_comment(id):
    form = CommentForm()
    if request.method == "POST" and form.validate_on_submit():
        comment = get_comment_model()(
            content=form.content.data,
            author_id=current_user.id,
            post_id=id
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("views.post_detail", id=id))

@login_required
@views.route("/edit-comment/<int:post_id>/<int:comment_id>", methods=["POST"])
def edit_comment(post_id, comment_id):
    comment = get_comment_model().query.filter_by(id=comment_id).first() # 수정할 댓글을 특정해야 한다.
    form = CommentForm() # Form으로 데이터를 받아온다.
    if current_user.username == comment.user.username:
        if form.validate_on_submit():
            comment.content = form.content.data
            db.session.commit()
            return redirect(url_for("views.post_detail", id=post_id))
        else:
            print("validation failed!")
    else:
        return abort(403)

@views.route("/contact")
def contact():
    return render_template("contact.html", user=current_user)

blog/templates/about.html
{% extends 'base.html' %}

{% block title %}About ME{% endblock %}

{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{ url_for('static', filename='assets/img/about-bg.jpg') }}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur
                    voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam
                    ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque
                    architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum
                    in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid
                    ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit
                    tempora!</p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/base.html
{# <nav>, <footer> 만 있는 파일 #}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    {# 변화하는 부분 #}
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>


    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>


</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                                        href="{{ url_for('views.home') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                                        href="{{ url_for('views.about') }}">About</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                                        href="{{ url_for('views.categories_list') }}">Categories</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('views.contact') }}">Contact</a>
                </li>


                {% if user.is_authenticated %}
                    {# 유저가 로그인했다면 보일 것들 : "Welcome, username", "Logout" 이고, user 정보가 넘어가야 함. #}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="color: red"
                                            href="#">welcome, {{ user.username }}!</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="color: red"
                                            href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}


                {% if not user.is_authenticated %} {# 그리고, 로그인한 상태가 아니라면... #}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                                            href="{{ url_for('auth.signup') }}">Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                                            href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>


{# 변화하는 부분 #}
{% block header %}{% endblock %}

{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {# 카테고리 == error 이라면, 실패 메시지를 출력 #}
            {% if category == "error" %}
                <div class="alert alert-danger alert-dismissable fade show" role="alert" style="text-align: center">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
                {# 그렇지 않다면, 성공 메시지를 출력 #}
            {% else %}
                <div class="alert alert-success alert-dismissable fade show" role="alert" style="text-align: center">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}


{# 변화하는 부분 #}
<div class="content-wrapper">
    {% block content %}{% endblock %}
</div>

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>


<!-- Core theme JS-->
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>


</body>
</html>

blog/templates/categories_list.html
{% extends 'base.html' %}

{% block title %}All Categories{% endblock %}

{% block header %}
    <!-- Page Header-->
    <header class="masthead"
            style="background-image: url({{ url_for('static', filename='assets/img/categories-bg.jpeg') }})">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>All Categories</h1>
                        <span class="subheading">Blog categories...</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-10">


                {% for category in categories %}
                    <!-- Category item-->
                    <div class="post-preview">
                        <a href="{{ url_for('views.post_list', id=category.id) }}">
                            <h2 class="post-title">{{ category.name }}</h2>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4"/>
                {% endfor %}


            </div>
        </div>
    </div>
{% endblock %}

blog/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{ url_for('static', filename='assets/img/contact-bg.jpg') }}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <span class="subheading">Have questions? I have answers.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon
                    as possible!</p>
                <div class="my-5">
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                        <div class="form-floating">
                            <input class="form-control" id="name" type="text" placeholder="Enter your name..."
                                   data-sb-validations="required"/>
                            <label for="name">Name</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="email" type="email" placeholder="Enter your email..."
                                   data-sb-validations="required,email"/>
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..."
                                   data-sb-validations="required"/>
                            <label for="phone">Phone Number</label>
                            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is
                                required.
                            </div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" id="message" placeholder="Enter your message here..."
                                      style="height: 12rem" data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.
                            </div>
                        </div>
                        <br/>
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                                To activate this form, sign up at
                                <br/>
                                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>
                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <div class="d-none" id="submitErrorMessage">
                            <div class="text-center text-danger mb-3">Error sending message!</div>
                        </div>
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block header %}
    <header class="masthead" style="background-image: url('{{ url_for('static', filename='assets/img/login-bg.jpg') }}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Login</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}

    <!-- Main Content-->
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="my-5">
                        <form id="contactForm" method="POST">
                            {{ form.csrf_token }}
                            <div class="form-floating">
                                <input class="form-control" id="email" type="email" placeholder="Enter your email..." name="email"
                                       data-sb-validations="required"/>
                                <label for="email">Email</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">A Email is required.</div>
                            </div>
                            <div class="form-floating">
                                <input class="form-control" id="password" type="password" placeholder="Enter your password..." name="password"
                                       data-sb-validations="required,email"/>
                                <label for="password">Password</label>
                                <div class="invalid-feedback" data-sb-feedback="password:required">An password is required.
                                </div>
                                <div class="invalid-feedback" data-sb-feedback="password:required">Email is not valid.</div>
                            </div>
                            <br/>
                            <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">
                                LOGIN
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>



{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}


{% block header %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <div id="title-wrapper"><h1>{{ post.title }}</h1></div>
                        <span class="meta">
                            <div id="author-wrapper"><p>Posted by : <a href="#!">{{ post.user.username }}</a></p></div>
                            <p>created_at : {{ post.created_at }}</p>
                            {% if post.user.username == current_user.username %}
                                <button class="btn btn-info" id="edit-button">
                                <a href="{{ url_for("views.edit_post", id=post.id) }}">Edit</a>
                            </button>
                            {% endif %}
                            </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 mb-5 col-xl-7" id="content-wrapper">
                    {{ post.content }}
                </div>
            </div>
            <hr/>
            <!--comment -->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body" id="comment-wrapper">
                        <!-- Comment form-->
                        <form class="mb-4" method="post" action="{{ url_for("views.create_comment", id=post.id) }}">
                            {{ form.csrf_token }}
                            <textarea class="form-control mb-3" rows="3" name="content"
                                      placeholder="Join the discussion and leave a comment!"></textarea>
                            <div style="text-align: right">
                                <button class="btn btn-info" id="submitButton"
                                        style="width: 150px;height: 45px; font-size: 12px;" type="submit">
                                    Comment
                                </button>
                            </div>
                        </form>
                        {% for comment in comments %}
                            <!-- Single comment-->
                            <div class="d-flex">
                                <div class="flex-shrink-0"><img class="rounded-circle"
                                                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
                                                                alt="...">
                                </div>
                                <div class="ms-3">
                                    <div class="fw-bold">{{ comment.user.username }}</div>
                                    {{ comment.content }}
                                </div>
                            </div>
                            {% if current_user.username==comment.user.username %}
                                <!-- 수정 버튼 -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                        data-bs-target="#editCommentModal{{ comment.id }}">
                                    Edit comment
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="editCommentModal{{ comment.id }}" tabindex="-1"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Comment id
                                                    : {{ comment.id }} Edit</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <form method="post" class="form-control"
                                                  action="{{ url_for("views.edit_comment", post_id=post.id, comment_id=comment.id) }}">
                                                {{ form.csrf_token }}
                                                <div class="modal-body">
                                                    <input type="text" class="form-control" name="content"
                                                           value="{{ comment.content }}"/>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                            data-bs-dismiss="modal">
                                                        Close
                                                    </button>
                                                    <button type="submit" class="btn btn-primary">Edit comment</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </article>

{% endblock %}